apiVersion: v2
name: streamverse
description: StreamVerse Microservices Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "13.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "26.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled

maintainers:
  - name: StreamVerse Team
    email: team@streamverse.io
